# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-04 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyfundraising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='\u90ae\u7bb1'),
        ),
    ]
