# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 06:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyfundraising', '0002_auto_20170304_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('club', '\u793e\u56e2'), ('market', '\u5546\u5bb6')], default='club', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='contacts',
            field=models.CharField(max_length=50, verbose_name='\u8054\u7cfb\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='item',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=30, verbose_name='\u9898\u76ee'),
        ),
    ]
