# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyfundraising', '0003_auto_20170315_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='easyfundraising.User', verbose_name='\u4f5c\u8005'),
        ),
    ]
