# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyfundraising', '0004_auto_20170315_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['pubtime']},
        ),
    ]
