# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyfundraising', '0005_auto_20170315_1529'),
        ('easyfundraising', '0005_auto_20170315_2258'),
    ]

    operations = [
    ]
