# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 08:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('contents', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents')),
                ('pubtime', models.DateTimeField(auto_now=True)),
                ('contacts', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=30, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name='\u5b66\u6821')),
                ('social_name', models.CharField(max_length=50, verbose_name='\u793e\u56e2\u540d')),
                ('phone_num', models.CharField(max_length=11, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='easyfundraising.User')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='easyfundraising.User'),
        ),
    ]
