# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-26 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('easyfundraising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name='\u5b66\u6821')),
                ('social_name', models.CharField(max_length=50, verbose_name='\u793e\u56e2\u540d')),
                ('phone_num', models.CharField(max_length=11, verbose_name='\u7535\u8bdd\u53f7\u7801')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='socialname',
        ),
        migrations.AddField(
            model_name='item',
            name='pubtime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 26, 5, 7, 13, 107000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='easyfundraising.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='easyfundraising.User'),
        ),
    ]
